### PR TITLE
BERT: add profiler, use dev_data for inference

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
- add profiler: export GLUONNLP_BERT_PROFILING=1;
- use dev_data for inference
- add max_len to the file name of saved parameter

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
@pengxin99 @eric-haibin-lin Please review. Do we need to set dropout=0 in inference?

**Review by eric-haibin-lin — COMMENTED** [review]
Dropout in inference mode ignores the provided dropout param and simply performs a copy. So the model behavior is the same. Actually, I noticed that the Transformer blocks add dropout layers even if dropout is set to 0 https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/transformer.py#L109, which is bad for inference due to extra copies. We should avoid adding the `Dropout` layer if self._dropout == 0. This is a low hanging fruit :)

**Comment by eric-haibin-lin** [comment]
the profiler change looks good

**Comment by TaoLv** [comment]
I want to avoid the 'copy' in inference by setting dropout=0 in the inference model. For training dropout is still 0.1. But seems it will fail to load the saved pre-trained model.

**Comment by eric-haibin-lin** [comment]
@TaoLv what err msg did you see?

**Comment by pengxin99** [comment]
i use the dropout=0 and got this log:

> AssertionError: Parameter 'classifier.0.weight' is missing in file 'out_dir/MRPC_128_valid_best.params', which contains parameters: 'bert.encoder.position_weight', 'bert.encoder.layer_norm.gamma', 'bert.encoder.layer_norm.beta', ..., 'bert.pooler.weight', 'bert.pooler.bias', 'classifier.1.weight', 'classifier.1.bias'. Set allow_missing=True to ignore missing parameters.

**Review by pengxin99 — COMMENTED** [review]
LGTM, except confused by the dropout

**Comment by TaoLv** [comment]
Thank you @pengxin99 . Any idea, @eric-haibin-lin ? I thought dropout could be skipped safely in inference even the model is trained with dropout=0.1.

**Comment by eric-haibin-lin** [comment]
It might be caused by the fact that some dropout layers are added to `nn.Sequential`, causing index changes. For example: https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/bert.py#L107-L110 . Do you still get this err if the dropout rate for BERTClassifier remains 0.1?

**Comment by TaoLv** [comment]
No, with rate=0.1 everything goes well. But as you mentioned, there would be implicit memory copy in dropout operator. Anyway it's not a big deal as dropout takes <1% execution time in the profiling.

**Comment by TaoLv** [comment]
Merged. @pengxin99 @juliusshufan

**Pull request merged**
